# Generated by Django 6.0.4 on 2026-04-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1CB3FE', help_text='Hex colour e.g. #1CB3FE', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTypeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_assignment', to='teams.team')),
                ('team_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='organisation.teamtype')),
            ],
            options={
                'verbose_name': 'Team type assignment',
                'verbose_name_plural': 'Team type assignments',
            },
        ),
    ]
