# Generated by Django 5.2.13 on 2026-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0005_alter_user_messages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_messages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
